import { describe, expect, it } from 'vitest'
import { blackPrice } from './optionMath.js'
import { fitForward, selectCalendarStrikes, StrikeSelectionError, type ChainQuote } from './calendarStrikes.js'

/**
 * Builds a synthetic chain from Black-76 with a realistic SPX skew.
 *
 * Testing the selection against a chain generated by the same model would only
 * prove the solver inverts itself, which the option math tests already cover.
 * What matters here is the skew: volatility rises as the strike falls, exactly
 * as SPX does, so a selection that quietly assumed one at-the-money volatility
 * across the chain would place the put strike visibly wrong and fail.
 */
function syntheticChain(options: {
  forward: number
  years: number
  discountFactor: number
  /** Volatility at the money, before skew. */
  atmVol: number
  /** Volatility added per 1% the strike sits below the forward. */
  skewPerPercent: number
  spread?: number
  strikes?: number[]
}): ChainQuote[] {
  const {
    forward,
    years,
    discountFactor,
    atmVol,
    skewPerPercent,
    spread = 0.4,
    strikes = defaultStrikes(forward)
  } = options

  const quotes: ChainQuote[] = []
  for (const strike of strikes) {
    const moneyness = ((forward - strike) / forward) * 100
    const volatility = Math.max(0.05, atmVol + skewPerPercent * moneyness)
    for (const right of ['call', 'put'] as const) {
      const price = blackPrice({ forward, strike, years, volatility, discountFactor, right })
      quotes.push({
        ticker: `O:SPXW260316${right === 'call' ? 'C' : 'P'}${String(strike * 1000).padStart(8, '0')}`,
        strike,
        right,
        bid: Math.max(0.05, price - spread / 2),
        ask: price + spread / 2,
        ageMs: 0
      })
    }
  }
  return quotes
}

function defaultStrikes(forward: number): number[] {
  const centre = Math.round(forward / 5) * 5
  const strikes: number[] = []
  for (let strike = centre - 1200; strike <= centre + 1200; strike += 5) strikes.push(strike)
  return strikes
}

const FORWARD = 6810
const YEARS = 14 / 365
const DISCOUNT = 0.9984

describe('fitForward', () => {
  it('recovers the forward and discount factor from quotes alone', () => {
    const quotes = syntheticChain({
      forward: FORWARD,
      years: YEARS,
      discountFactor: DISCOUNT,
      atmVol: 0.16,
      skewPerPercent: 0.012
    })

    const fit = fitForward(quotes, 6800, YEARS)
    expect(fit).not.toBeNull()
    expect(fit!.forward).toBeCloseTo(FORWARD, 4)
    expect(fit!.discountFactor).toBeCloseTo(DISCOUNT, 6)
    expect(fit!.residualRms!).toBeLessThan(1e-6)
  })

  it('returns null when too few strikes near the money are two-sided', () => {
    const quotes = syntheticChain({
      forward: FORWARD,
      years: YEARS,
      discountFactor: DISCOUNT,
      atmVol: 0.16,
      skewPerPercent: 0,
      strikes: [6800, 6805]
    })
    expect(fitForward(quotes, 6800, YEARS)).toBeNull()
  })

  it('ignores crossed and one-sided quotes', () => {
    const quotes = syntheticChain({
      forward: FORWARD,
      years: YEARS,
      discountFactor: DISCOUNT,
      atmVol: 0.16,
      skewPerPercent: 0.012
    })
    // Cross a near-the-money pair; the fit must not be dragged by it.
    for (const quote of quotes) {
      if (quote.strike === 6810) {
        quote.bid = 500
        quote.ask = 400
      }
    }
    const fit = fitForward(quotes, 6800, YEARS)
    expect(fit!.forward).toBeCloseTo(FORWARD, 4)
  })
})

describe('selectCalendarStrikes', () => {
  const chain = syntheticChain({
    forward: FORWARD,
    years: YEARS,
    discountFactor: DISCOUNT,
    atmVol: 0.16,
    skewPerPercent: 0.012
  })

  it('lands within half a strike increment of the target delta on both sides', () => {
    const selection = selectCalendarStrikes({ quotes: chain, spot: 6800, years: YEARS, targetDelta: 0.3 })

    expect(Math.abs(selection.put.delta)).toBeGreaterThan(0.28)
    expect(Math.abs(selection.put.delta)).toBeLessThan(0.32)
    expect(selection.call.delta).toBeGreaterThan(0.28)
    expect(selection.call.delta).toBeLessThan(0.32)
  })

  it('puts both short strikes outside the forward', () => {
    const selection = selectCalendarStrikes({ quotes: chain, spot: 6800, years: YEARS, targetDelta: 0.3 })
    expect(selection.put.strike).toBeLessThan(selection.forward)
    expect(selection.call.strike).toBeGreaterThan(selection.forward)
  })

  it('places the put further out than the call, because of the skew', () => {
    /*
     * With downside volatility richer than upside, a 30 delta put sits further
     * from the forward in points than a 30 delta call. A single at-the-money
     * volatility would place them symmetrically, so this is the assertion that
     * the per-strike solve is doing real work.
     */
    const selection = selectCalendarStrikes({ quotes: chain, spot: 6800, years: YEARS, targetDelta: 0.3 })
    const putDistance = selection.forward - selection.put.strike
    const callDistance = selection.call.strike - selection.forward
    expect(putDistance).toBeGreaterThan(callDistance)
    expect(selection.put.impliedVolatility).toBeGreaterThan(selection.call.impliedVolatility)
  })

  it('moves the strikes outward as the target delta falls', () => {
    const thirty = selectCalendarStrikes({ quotes: chain, spot: 6800, years: YEARS, targetDelta: 0.3 })
    const fifteen = selectCalendarStrikes({ quotes: chain, spot: 6800, years: YEARS, targetDelta: 0.15 })

    expect(fifteen.put.strike).toBeLessThan(thirty.put.strike)
    expect(fifteen.call.strike).toBeGreaterThan(thirty.call.strike)
  })

  it('rejects a strike whose bid is below the floor', () => {
    const cheap = chain.map((quote) => ({ ...quote, bid: 0 }))
    expect(() => selectCalendarStrikes({ quotes: cheap, spot: 6800, years: YEARS, targetDelta: 0.3 }))
      .toThrow(StrikeSelectionError)
  })

  it('refuses a chain it cannot fit a forward to', () => {
    expect(() =>
      selectCalendarStrikes({ quotes: chain.slice(0, 2), spot: 6800, years: YEARS, targetDelta: 0.3 })
    ).toThrow(/parity/i)
  })

  it('rejects a nonsensical target delta', () => {
    expect(() => selectCalendarStrikes({ quotes: chain, spot: 6800, years: YEARS, targetDelta: 1.4 }))
      .toThrow(StrikeSelectionError)
  })
})
